// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCMSAccountAndAbout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCMSAccountAndAbout));
        
        string IMigrationMetadata.Id
        {
            get { return "202305312008586_addCMSAccountAndAbout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
