// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMember));
        
        string IMigrationMetadata.Id
        {
            get { return "202306031103510_addMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
